version: '2'
services:
  mypostgres:
    image: "postgres:9.4"
    env_file:
      - ./secrets.env
  web:
    build: .
    env_file:
      - ./secrets.env
    command: npm start
    depends_on:
      - mypostgres
    ports:
      - 8080:8080